# Gradle
org.gradle.jvmargs=-Xmx1G -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true

# Fabric Properties
minecraft_version=26.2
loader_version=0.19.5

# Mod Properties
mod_version=1.0.0
maven_group=me.andromedov
archives_base_name=paradisepaints

# Dependencies
fabric_version=0.159.0+26.2
